{% set name = "arize-phoenix-client" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix_client-{{ version }}.tar.gz
  sha256: 487e3db2c4dfb366dd7c2aefee858a4c29425c3add41cd722be4c490d30b5fa4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - httpx
    - typing_extensions
    - tqdm
    - openinference-semantic-conventions
    - opentelemetry-sdk
    - opentelemetry-exporter-otlp

test:
  imports:
    - phoenix.client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: LLM Observability
  home: https://github.com/Arize-ai/phoenix/
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RogerHYang
