{% set name = "arize-phoenix-client" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix_client-{{ version }}.tar.gz
  sha256: 212e4ee4f0e93b2183f35b1b37f2966d72c52bb93754fd94d08e4c9d88ebb070

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - httpx
    - typing_extensions
    - tqdm
    - openinference-semantic-conventions
    - openinference-instrumentation
    - opentelemetry-sdk
    - opentelemetry-exporter-otlp

test:
  imports:
    - phoenix.client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: LLM Observability
  home: https://github.com/Arize-ai/phoenix/
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RogerHYang
