{% set name = "arize-phoenix-client" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix_client-{{ version }}.tar.gz
  sha256: 112351c83b7f0bf3a79bb8b71051e558fc86e4f3a0529014ecfdf21ae707d47d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - httpx
    - typing_extensions

test:
  imports:
    - phoenix.client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: LLM Observability
  home: https://github.com/Arize-ai/phoenix/
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RogerHYang
